### PR TITLE
Attempt to fix Error on my first review each time I flip the card

### PR DESCRIPTION
**Pull request by evandrocoan**
fix https://github.com/kelciour/awesometts-anki-addon/issues/33

### CODE REVIEW

**Comment by kelciour** [comment]
Big thanks!

**Comment by DoctorToBeIn23** [comment]
Whats the update on this issue? Any idea how to get rid of it?

**Comment by evandrocoan** [comment]
IT should be fixed on the next release of the addons.

**Comment by kelciour** [comment]
Thanks again for the quick fix. It's been updated on AnkiWeb.

**Pull request merged**
